### ISSUE TITLE
process hangs when Timestamp is greater than 2^64.

### ISSUE THREAD

**Issue by shahdarshan1711** [silviucpp/erlcass#10]
I am using Code from Tag v2.4

Whenever I try to convert Timestamp to UUID as below, calling process hangs forever. 

`erlcass_uuid:gen_from_ts(67255124296721106952000).`

In logs it is showing below error in my application.
CRASH REPORT Process erlcass_uuid_proc with 0 neighbours crashed with reason: bad argument in call to erlcass_nif:cass_uuid_gen_from_time(<<>>, 67255124296721106952000) in erlcass_uuid:loop/1 line 94

And when I tried same scenario from Erlang shell, it shows below error and stuck there.
driver received: {'EXIT',<0.66.0>,badarg} 

When I checked code, I found that **erlcass_uuid:gen_from_ts** call never times out. So calling process is stuck always. And after process erlcass_uuid_proc crashed, it doesn't come up automatically through supervisor behaviour. Since it is not coming up subsequent calls from different process is failing to convert valid timestamp(value in range) as erlcass_uuid_proc is down.

-Thanks

**Comment by silviucpp** [comment]
Hello, 

Thanks  for reporting . I will test this scenario. Most probably I will throw an error as time internally the datastax driver it's using uint64 for storing the timestamp. Timestamp beeing number of milliseconds since the Epoch* (00:00:00 UTC on 1 January 1970)

Silviu

**Comment by shahdarshan1711** [comment]
Sure. Error is fine as datastax driver doesn't support. And can we add support for restart of process(uuid_proc) if it goes down as it will be helpful for subsequent requests. 

I am passing Timestamp in Microseconds to the function as we need microsecond level granularity.  I agree that it is very unlikely scenario, but if it fails, then subsequent calls also fails and that's where it creates problem for system.

Darshan

**Comment by silviucpp** [comment]
Hello Darshan,

I think you need to update the erlcass as time we did lot of changes in that area. There is no longer any gen_server there. 

But also keep in mind that even if you need microseconds as time the native driver is not supporting best think I can do is just return an error :) 

Silviu

**Comment by silviucpp** [comment]
BTW: changelog is here: https://github.com/silviucpp/erlcass/blob/master/CHANGELOG.md

2.8 is still under development as time we make public releases after library goes in production for some time on our services. And at this moment on our side is only in prelive stage.

Silviu

**Comment by shahdarshan1711** [comment]
Hello,

I can see there has been lots of code/design change between version I am using and latest one. Let me see if I can upgrade to latest one with tight release schedule. Looks like it can fix the problem.

I have been using Microsecond for some time now and haven't seen any issue. Do you see any major/minor issue that I should be aware of? 

Thanks,
Darshan

**Comment by silviucpp** [comment]
Hello,
I don't think there is any change in interface that might break your code, excepting:
- Integrated lager as dependency
- Removed support for the following methods: set_cluster_options/1, create_session/1, and set_log_function/1

Regarding the timestamp issue only problem I can see is that you go much faster out of accepted range.

Please let me know if in case you update you have the same problem,

Silviu

**Comment by silviucpp** [comment]
Hello Darshan,

I checked on the last erlcass version from master and I get :
```erlang
erlcass_uuid:gen_from_ts(67255124296721106952000).
{error,badarg}
```

So problem seems resolved,

Let e know how works for you,
Silviu

**Comment by silviucpp** [comment]
Hello,
I'll close this for the moment as time it's fixed in the last version. In case you have any issue please feel free to open it again.

Silviu

**Comment by shahdarshan1711** [comment]
Hello,

I checked with master branch and call `erlcass_uuid:gen_from_ts(67255124296721106952000).` is returning as you have explained. But when I tried with tag v2.7 codebase, it is throwing exception. I can see in v2.8 changelog that you have fix that also. 

When we build our application, we get source code through rebar every time. So I can't use master branch as it keeps on changing. So we want to use tag v2.8 . So when can I expect v2.8 released?

There is one issue with master branch. When I set keyspace in app.config which is not created, `application:start(erlcass)` doesn't throw any error. It returns **ok**. But further operation is failing.  In version v2.4 , `erlcass:create_session([{keyspace, <<"test_keyspace">>}])` used to throw error if keyspace doesn't exists and at that we connect without keyspace `erlcass:create_session([])` and create keyspace by ourself. Since support is removed for create_session, we have lost that functionality. 

Further digging into code, I can see [here](https://github.com/silviucpp/erlcass/blob/master/src/erlcass.erl#L341) that, you are getting `{error,<<"Keyspace 'test_keyspace' does not exist">>}` in Result parameter but it is just being ignored. So if keyspace doesn't exist, then also `application:start(erlcass)` succeed and our application doesn't know if it is really connected or not.

So is there any particular reason to start application if not able to connect to keyspace?

Thanks,
Darshan

**Comment by silviucpp** [comment]
Hello,

1. regarding rebar: you can use something to get a specific commit even if it's not tagged:

{erlcass, ".*", {git, "https://github.com/silviucpp/erlcass.git", "1435301026e450b6970b7cc82a661f6c7b375fe2"}}

We will release 2.8 later this time.

2. It's a bug . I will change this most probably to not start the app until the keyspace is not created. It's this ok for you ?

**Comment by shahdarshan1711** [comment]
Hello,

Thanks for rebar info. I will do that way.

That's fine for me if it is throwing proper error for not starting. So in my application, I can create keyspace if it is not there or bring down my application if it is not able to connect to Cassandra.

Thanks for your help,
Darshan

**Comment by silviucpp** [comment]
Hello Darshan,

Looking to the code it's hard to stop the app when the keyspace is not existing. Reasons being:

1. we might want In the future to add support for multiple clusters configs (which means will be multiple erlcass pools with each own settings). So this instances should work separated and not affect each other
2. the app it's starting a supervisor that it's spawning the erlcass process. If erlcass process it's crashing it's restarted until limit is reached and then app dies.

What I think we can do to provide more control is:

1. allow the user to specify a query for creating the keyspace in case the keyspace is not available.

2. Expose a method in erlcass like `erlcass:connection_result/0` which returns ok if connection completed or the error received  when tried to connect. then you can decide if you want to stop the app or do something else

What do you think ?

Silviu

**Comment by shahdarshan1711** [comment]
Hello,

I am fine with the approach you suggested. Method like `erlcass:connection_result/0` will be useful. About specifying query to create keyspace will do the job, but where you are planning to give option to specify query? 

I liked the older idea(having create_session and cluster_option) much more user friendly, as it gives more  control. It separates all the functionality in different logical functions instead of keeping everything in application start. I may not be knowing all code complexity. So let me know your thoughts on this. 

Btw, I have integrated latest from master branch in my application without any major issue. 

Darshan

**Comment by silviucpp** [comment]
Hello,

I have no plan to add back create_session and cluster_option, maybe we will do this later if we add support for multiple pools under another format.

Regarding the create keyspace feature I can change the keyspace option like:

{keyspace, <<"name">>} - won't call anything to create the keyspace in case it's not available
{keyspace, {<<"name">>, <<"create_query">>}} - In case the keyspace is not there will create that keyspace using the specified query and reconnect the session to that keyspace

Silviu

**Comment by shahdarshan1711** [comment]
Hello,

This kinda option will do.

I have one more question. As I told you I am using `gen_from_ts ` with microsecond timestamp instead of millisecond. There is drawback of doing this as you won't get same timestamp using `get_ts ` function as while converting to UUID it is expecting input as millisecond. So giving microsecond timestamp will work as far as we not planning to get timestamp back from UUID. If we want microsecond level granularity for our events, is there any other way?

Darshan

**Comment by silviucpp** [comment]
Hello,

There is no way. The datastax driver works with milliseconds.

Silviu

**Comment by silviucpp** [comment]
Closing this as time original issue is fixed in last master
