### ISSUE TITLE
support user-defined type?

### ISSUE THREAD

**Issue by viplifes** [silviucpp/erlcass#13]
How soon do you plan to add support user-defined type?
Thanks!

**Comment by silviucpp** [comment]
Hello,

Feel free to implement and send a pull request. I'm happy to review it. At this moment I don't have any plan to implement this as time I don't use this in the projects where we are running erlcass and cassandra and also I don't have too much time to work on this now.

**Comment by silviucpp** [comment]
Hello,

I decided to add support for this in the next version. I'm already started to work on this but the fix will go on a branch where I have some small breaking API changes. 

Silviu

**Comment by silviucpp** [comment]
This was implemented in the master and will be part of 2.9 release.

**Comment by silviucpp** [comment]
You can look on the examples for UDT tests: https://github.com/silviucpp/erlcass/blob/master/test/integrity_test_SUITE.erl#L346

Basically UDT is decoded as proplist

**Comment by viplifes** [comment]
Thanks!
