### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by viplifes** [silviucpp/erlcass#14]
erlcass v2.8
OTP 19.3

```sql
CREATE TABLE channel.test (
    id text, 
    name text,
    PRIMARY KEY (id)
);
```

```erlang
erlcass:add_prepare_statement(test, "SELECT * FROM channel.test WHERE id=?").
```

```erlang
erlcass:execute(test, [<<"test">>, <<"test">>]).
```
After executed query, we get - Segmentation fault

**Comment by silviucpp** [comment]
Thanks for reporting. 
I will test to fix the problem . but looking on it seems also a problem with the way you are using prepared statements:

You have only one parameter id = ? but you send two arguments. 

Correct is :

erlcass:execute(test, [<<"test">>]).

**Comment by silviucpp** [comment]
Fixed in last master. Instead crashing will return `{error,badarg}`

**Comment by viplifes** [comment]
Thanks. master works correctly!
