### ISSUE TITLE
Need help to integrate in ejabberd 17.08

### ISSUE THREAD

**Issue by naemakram** [silviucpp/erlcass#17]
Hi everyone,

I need to integrate erlacass in ejabberd as I am integrating new database. I have both thing installed and working separate but now I need to call erlcass from inside the ejabbed modules , can anyone please guide me how I can do it?

**Comment by silviucpp** [comment]
Hi,
I don't think here is the appropriate place for such question. 
Anyway integrating erlcass should be done in the same way you integrate in any other erlang appliction. Add erlcass to deps, add config in app.config prepare your statements somewhere when your app it's starting and then execute them wherever you need.

Silviu
