### ISSUE TITLE
Stream rows

### ISSUE THREAD

**Issue by Capitan-KoLiBer** [silviucpp/erlcass#23]
Recently i worked with standard Node.JS Cassandra Driver,
that implements row streams that can call a callback whenever a row receives,

have your driver implements streams ? or you implement it as a feature ?

**Comment by silviucpp** [comment]
Hello,

From what I'm aware of there is nothing into the Datastax cpp driver that describes the functionality you are mentioning.

Yes the results comes in the datastax driver in a async callback but not independent. All raws in the same callback and I'm sending them async as well as an erlang message to the calling process.

Are you sure that functionality is not some sort of emulation ? I mean I can easily do it but from a performance will sucks.

**Comment by Capitan-KoLiBer** [comment]
Hi :)
I skim the Node.JS Driver and i find out driver will pages result in smaller sizes, iterate pages and emits a callback on every row in every page

does `erlcass` driver has a way to change page sizes ? or it's static ? and how it can handle multi pages on async query ?
