### ISSUE TITLE
Hex package build failure because Makefile, build_deps.sh missing

### ISSUE THREAD

**Issue by whitedr** [silviucpp/erlcass#28]
Hi,

After seeing #26 was addressed, I just tried using erlcass in a mix project by adding it as a dependency like this:

```
{:erlcass, "~> 3.2"}
```

I could pull the dep just fine with `mix deps.get`, but when I tried to compile it I get the error:

```
erlcass_test $ mix compile
===> Compiling goldrush
===> Compiling lager
===> Fetching rebar3_hex ({pkg,<<"rebar3_hex">>,<<"4.1.0">>})
===> Version cached at /Users/dwhite/.cache/rebar3/hex/default/packages/rebar3_hex-4.1.0.tar is up to date, reusing it
===> Compiling rebar3_hex
===> Compiling erlcass
make: *** No rule to make target `nif_compile'.  Stop.
===> Hook for compile failed!

** (Mix) Could not compile dependency :erlcass, "/Users/dwhite/.asdf/installs/elixir/1.7.1/.mix/rebar3 bare compile --paths "/Users/dwhite/src/yieldbot/erlcass_test/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile erlcass", update it with "mix deps.update erlcass" or clean it with "mix deps.clean erlcass"
```

Looking into this more, it looks like in the `deps/erlcass` directory, the files: `Makefile` and `build_deps.sh` are missing which I believe is the root cause of this issue.  If I specify the dependency as a git dep like this:

```
{:erlcass, git: "git@github.com:silviucpp/erlcass.git"}
```

Then it is pulled down and compiles just fine.

**Comment by silviucpp** [comment]
You are right ! I'm not familiar with hex and @goncalotomas helped me with some instructions on how to publish the package. I have to check the hex documentation and see how to specify to include this files as well in the package.

@goncalotomas any idea ?

**Comment by silviucpp** [comment]
OK I found the problem. I fixed in master and published another package.
Also tested with rebar3 and seems fine. Please confirm

**Comment by whitedr** [comment]
@silviucpp I just tried it again and it worked perfectly.  Thanks for getting that fixed up so quickly!

**Comment by silviucpp** [comment]
Thanks for your feedback

Silviu
