### ISSUE TITLE
How to profiling the write performance?

### ISSUE THREAD

**Issue by pernghh** [silviucpp/erlcass#30]
Hi,
 
I got a module that using erlcass 2.8 to save data to Cassandra. Currently I met a performance issue and I have no idea to profiling the performance. I try the 

`cassandra-stress write n=1000000`

on the DB server and got the result :

Results:
Op rate                   :   16,139 op/s  [WRITE: 16,139 op/s]
Partition rate            :   16,139 pk/s  [WRITE: 16,139 pk/s]
Row rate                  :   16,139 row/s [WRITE: 16,139 row/s]
Latency mean              :   12.3 ms [WRITE: 12.3 ms]
Latency median            :    9.7 ms [WRITE: 9.7 ms]
Latency 95th percentile   :   28.0 ms [WRITE: 28.0 ms]
Latency 99th percentile   :   73.6 ms [WRITE: 73.6 ms]
Latency 99.9th percentile :  120.2 ms [WRITE: 120.2 ms]
Latency max               :  219.3 ms [WRITE: 219.3 ms]
Total partitions          :  1,000,000 [WRITE: 1,000,000]
Total errors              :          0 [WRITE: 0]
Total GC count            : 0
Total GC memory           : 0.000 KiB
Total GC time             :    0.0 seconds
Avg GC time               :    NaN ms
StdDev GC time            :    0.0 ms
Total operation time      : 00:01:01

But in my module, I need 3~10+ ms to process 4 insert commands (only with less than 10 fields in a row).  I have already make it into a batch command. The module's server and Cassandra server is in the same LAN. Dues to I just call function likes:

`   {ok, Stm1} = erlcass:bind_prepared_statement(insert_message), 
    ok = erlcass:bind_prepared_params_by_index(Stm1, [UID, LUser, Peer, Timestamp, xml:element_to_binary(Xml), Body, jlib:atom_to_binary(Dir)]),
`

`   {ok, Stm2} = erlcass:bind_prepared_statement(insert_message_by_ts), 
    ok = erlcass:bind_prepared_params_by_index(Stm2, [LUser, Timestamp, UID]),`

` {ok, Stm3} = erlcass:bind_prepared_statement(insert_message_by_peer_ts), 
    ok = erlcass:bind_prepared_params_by_index(Stm3, [LUser, Peer, Timestamp, UID]),`

`   {ok, Stm4} = erlcass:bind_prepared_statement(insert_peer_list_by_ts), 
    ok = erlcass:bind_prepared_params_by_index(Stm4, [LUser, Peer, binary_to_integer(jlib:timestamp()), Timestamp]),`

`erlcass:batch_execute(?CASS_BATCH_TYPE_LOGGED, [Stm1, Stm2, Stm3, Stm4], [{consistency_level, ?CASS_CONSISTENCY_QUORUM}]),` 

Then I got really bad performance ( less than 1000 row/second), so I need to find out what happened inside the erlcass module.

Are there some debug helper functions can help me to profiling where is the bottleneck of my system?
Maybe it just caused by my error setting of erlcass?

Thank you~
Eric

**Comment by silviucpp** [comment]
You are comparing apples with oranges. batch_execute It's running cql batches (https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlBatch.html)

And as you can read: Important: Only use a multiple partition batch when there is no other viable option, such as asynchronous statements. Multiple partition batches may decrease throughput and increase latency.

If you want to do a comparable load test with cassandra-stress you should use erlcass:async_execute

Something like the scripts we have to load test the read peformances:

https://github.com/silviucpp/erlcass/tree/master/benchmarks
