### ISSUE TITLE
Connect/Reconnect to cassandra cluster

### ISSUE THREAD

**Issue by dubrovine** [silviucpp/erlcass#41]
Hello there to everyone.
Could someone put me to the right direction

I am getting this warnings on MacOs Mojave 10.14.5 (18F132)::
`<<"Connection pool was unable to reconnect to host ******** because of the following error: Connect error 'operation not permitted'">> on <<"virtual void cass::Pool::on_close(cass::Connection *)">> at file src/pool.cpp line 420`

but I can make any queries to cassandra database through already started application

libuv 1.29.1
openssl 1.0.2r

is there any steps to resolve this issue ?
______

**Also I have another device with Ubuntu 18.04 (and there is no problem with cassandra)

**Comment by silviucpp** [comment]
That error comes from server. Is not a client error. Do you have any sort of authentication enabled on that host ?

**Comment by silviucpp** [comment]
Check also the server logs and see what you find there

**Comment by dubrovine** [comment]
Yes we have authentication on the server side (and ip was excluded already)

we just checked the logs on the server and we can see that we don't have any cassandra logs when I'm receiving such warnings.
also we are seeing that connect was reset by client when I am trying connect to cassandra node

Might something between app and database

**Comment by silviucpp** [comment]
Client closes the connection when receives from server the error. We are using as well auth and we have no problem with this. 

I can't tell you exactly what's wrong without having knowledge on the setup itself. But I doubt it's a problem with driver itself. Most likely a config issue. How many cassandra nodes you have in your cluster ? all of them report this issue ? or only that host ?

**Comment by dubrovine** [comment]
We have three nodes and with two of them I am getting this error

**Comment by dubrovine** [comment]
Closing the issue!
today everything was fixed by itself (who knows might amazon made some "fixes" or something)
