### ISSUE TITLE
GCC9 support ? 

### ISSUE THREAD

**Issue by dubrovine** [silviucpp/erlcass#45]
Hello

I am trying to use erlcass driver with erlang23 (in docker container) and discovered that erlang image is fetching alpine-linux with GNU 9.3.0 by default

As I can see the latest version of erlcass is using cpp-driver 2.13.0vsn which doesn't support gcc9

is there anyway to update erlcass to the latest supported version ?
Seems like its supported since 2.14.0 `https://github.com/datastax/cpp-driver/releases`

thanx in advance

**Comment by silviucpp** [comment]
Will look into this soon

**Comment by silviucpp** [comment]
Master has already a fix for this. I'm planning to do more travis changes to cover more OS's and then I will also publish the hex package.
