### ISSUE TITLE
application:stop(erlcass) is blocked

### ISSUE THREAD

**Issue by al3chen** [silviucpp/erlcass#57]
start () ->
   application:start(erlcass),
   ok.

stop() -> 
  application:start(erlcass), %% block in there
  ok.  %% never run to here

I try erlcass in my app.  start erlcass is ok and all fucntion  work well.  but when I try stop erlcass. it block and never finish. I used prepare statement to aync insert something.  Should I need clean somthing before stop erlcass?

**Comment by silviucpp** [comment]
Hello,

No, you shouldn't do anything. Do you have a minimum steps to replicate this problem ? We are not able to do it. 

Silviu

**Comment by silviucpp** [comment]
Have you found the problem ? I'm wonder what was the issue.

**Comment by al3chen** [comment]
It is NOT a issue.  I am newcomer for erlang , In my app, I tried to call function other module to call application:stop(erlcass), it should be blocked.  The right logic is I should stop my app firstly, in my app stop callback function , call application:stop(erlcass), the erlcass will be stop.  I tested this was no any issue for erlcass start and stop.
