### ISSUE TITLE
How to connect to cluster with SSL?

### ISSUE THREAD

**Issue by Vkutovoy92** [silviucpp/erlcass#62]
Hi, I'm trying to connect to Amazon Keyspaces and I have to add sf-class2-root.crt certificate and can't understand how. I see 
```
{ssl, [
        {trusted_certs, CertsList::list()},
        {cert, Cert::binary()},
        {private_key, {PrivateKey::binary(), KeyPassword::binary()}},
        {verify_flags, VerifyFlags::integer()}
       ]
}
```
but it doesn't work. How to do it? 

AWS says that "Amazon Keyspaces requires the use of Transport Layer Security (TLS) to help secure connections with clients."
And in other examples like a GO driver it requires just add one param with certificate path.
https://docs.aws.amazon.com/keyspaces/latest/devguide/using_go_driver.html

Error is

```
{{badmatch,{error,<<"Unable to load certificate">>}},
 [{erlcass_cluster,set_options,1,
```
I made 
 ```
 {ssl,
        [
          {cert, <<"/Users/vitalijkutovoj/Documents/sf-class2-root.crt">>},
          {verify_flags, 1}
        ]
      },
```
And tried different schemes to add it.

**Comment by silviucpp** [comment]
Unfortunately I don't have access to such cluster to assist you.

**Comment by Vkutovoy92** [comment]
> Unfortunately I don't have access to such cluster to assist you.

It works without sertificate so your driver works fine with AWS Keyspaces. We have been testing it about 1 month.
