### ISSUE TITLE
Can't start v4.1.2 -  {stop,{error,connect_session_timeout}

### ISSUE THREAD

**Issue by Vkutovoy92** [silviucpp/erlcass#64]
Hi again!
After update to v4.1.2 driver doesn't connect to Cassandra with error
`Supervisor erlcass_sup had child erlcass started with erlcass:start_link() at undefined exit with reason bad return value: {stop,{error,connect_session_timeout},shutdown,{state,undefined}} in context start_error`
When I rollback to v4.1.1 - it's ok, I suppose something was changed in  v4.1.2 about connection? My config

```
  {erlcass, [
    {log_level, 3},
    {keyspace, ?KEYSPACE},
    {cluster_options,[
      {contact_points, ?HOSTS},
     {port, 9042},
     {latency_aware_routing, true},
     {token_aware_routing, true},
     {number_threads_io, 4},
     {queue_size_io, 128000},
     {core_connections_host, 1},
     {tcp_nodelay, true},
     {tcp_keepalive, {true, 1800}},
     {default_consistency_level, 6}
   ]}
 ]}
```
I tried to add option
{connect_timeout, 60000},
And no result

Maybe problem because of new cpp-driver version?
v4.1.2 doesn't work on both MacOS (x64 and ARM) with the same reason.

**Comment by Vkutovoy92** [comment]
Version v4.1.1 + new _build/default/lib/erlcass/c_src/Makefile which you gave my yesterday + export LIBUV_ROOT_DIR="/opt/homebrew/opt/libuv" and it works fine! Maybe I need to make my custom driver version))

**Comment by silviucpp** [comment]
what cassandra version ?

**Comment by Vkutovoy92** [comment]
> what cassandra version ?

Cassandra 3.11.16 | CQL spec 3.4.4 | Native protocol v4

**Comment by silviucpp** [comment]
I fixed in the new release I just did . please confirm

**Comment by silviucpp** [comment]
callbacks in 2.17.1 seems broken: https://datastax-oss.atlassian.net/jira/software/c/projects/CPP/issues/CPP-995
I downgraded to 2.17.0
