### ISSUE TITLE
How to add multiple key/value pair in map using prepare statement?

### ISSUE THREAD

**Issue by shahdarshan1711** [silviucpp/erlcass#8]
I have created table that contains map as follow. I am using v2.4 tag version of erlcass.

`CREATE TABLE users (
  user_id text PRIMARY KEY,
  first_name text,
  last_name text,
  todo map<text,text>
);`

I want to insert multiple key/value. So I created prepare statement as below.

`erlcass:add_prepare_statement(test,<<"INSERT INTO users (user_id, todo) VALUES(?,?)">>).`

and I am running execute statement as below.

`erlcass:execute(test,1,[<<"user">>,<<"{ 'b' : 'birthday wishes to Bilbo', 'c': 'Check into Inn of Pracing Pony'}">>]).`

But it throws below exception.

`** exception error: bad argument
     in function  erlcass_nif:cass_statement_bind_parameters/3
        called as erlcass_nif:cass_statement_bind_parameters(<<>>,1,
                                                             [<<"user">>,
                                                              <<"{ 'b' : 'birthday wishes to Bilbo', 'c': 'Check into Inn of Pracing Pony'}">>])
     in call from erlcass:async_execute/3 (src/erlcass.erl, line 162)
     in call from erlcass:execute/3 (src/erlcass.erl, line 187)`

Let me know it's issue with erlcass or I am doing something wrong? If I am doing something wrong then please suggest correct way of doing it.

Thanks.

**Comment by silviucpp** [comment]
Hello,

I didn't tested on your scenario but there are examples in readme and also in the unit test files where I'm playing with maps:

https://github.com/silviucpp/erlcass/blob/master/test/integrity_test_SUITE.erl

Search for collection_types(_Config)

Silviu

**Comment by silviucpp** [comment]
Hello, 

Does the last comment helped you to fix your problem ?

Silviu

**Comment by shahdarshan1711** [comment]
Thanks. It certainly helped to fix the problem. It was the same thing I was looking for. In the readme, example was given for adding one key/value pair. The way I was giving multiple key/value pair was incorrect. Test-cases helped me giving value in correct format.

**Comment by silviucpp** [comment]
Nice,

I'll close this one.
