### ISSUE TITLE
Cassandra / CQL version compatibility status

### ISSUE THREAD

**Issue by weixiyen** [silviucpp/erlcass#9]
Hi there, was wondering which version of cassandra/CQL that erlcass currently supports.

Also, are you using this in production for your own project?  What sort of production load has erlcass handled so far?

Thanks!

**Comment by silviucpp** [comment]
Hello,

We are using this in production for long time in https://www.wowapp.com/ chat application and the project has enough load (unfortunately I can't make it public). 

Regarding the CQL versions supported as you can read also on the Datastax website the native driver is compatible with Apache Cassandra 1.2, 2.0, 2.1, 2.2 and 3.0, so all CQL versions are supported.

You can change the negotiated protocol version using protocol_version param (https://github.com/silviucpp/erlcass/wiki/Available-cluster-options)

Silviu
